apiVersion: apps/v1
kind: Deployment
metadata:
  name: aksdemo-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aksdemo
  template:
    metadata:
      labels:
        app: aksdemo
    spec:
      containers:
      - name: ACRsample1
        image: acrsample1.azurecr.io/bhanu9505508737/aksdemo:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: bhanubandi97
---
apiVersion: v1
kind: Service
metadata:
  name: aksdemo
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: aksdemo
