apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoaks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoaks
  template:
    metadata:
      labels:
        app: demoaks
    spec:
      containers:
      - name: demoaks
        image: acrsample1.azurecr.io/bhanu9505508737/demoaks:#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: PODNAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
      imagePullSecrets:
      - name: bhanubandi97
---
apiVersion: v1
kind: Service
metadata:
  name: demoaks
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: myapp